# Numpy

The NumPy library is the core library for scientific computing in Python. It provides a  high-performance multidimensional array object, and tools for working with these arrays. 

Use the following improt convention: # 

In [1]:
import numpy as np

# Numpy Arrays

# Creating Arrays

In [2]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

# Initial Placeholders# 

In [3]:
np.zeros((3,4)) #Create an array of zeros
np.ones((2,3,4),dtype=np.int16) #Create an array of ones
d = np.arange(10,25,5)#Create an array of evenly spaced values (step value)
np.linspace(0,2,9) #Create an array of evenlyspaced values (number of samples)
e = np.full((2,2),7)#Create a constant array
f = np.eye(2) #Create a 2X2 identity matrix
np.random.random((2,2)) #Create an array with random values
np.empty((3,2)) #Create an empty array

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

# I/O 
Saving & Loading on Disk

In [4]:
np.save('my_array' , a)
np.savez( 'array.npz', a, b)
np.load( 'my_array.npy')

array([1, 2, 3])

# Saving & Loading Text Files# 

In [ ]:
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter= ',')
np.savetxt( "myarray.txt", a, delimiter= " ")

# Asking For Help

In [7]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Inspecting Your Array

In [10]:
a.shape #Array dimensions
len(a)#Length of array
b.ndim #Number of array dimensions
e.size #Number of array elements
b.dtype  #Data type of array elements
b.dtype.name  #Name of data type
b.astype(int)#Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

# Data Types

In [16]:
np.int64 #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #Complex numbers represented by 128 floats
np.bool  #Boolean type storing TRUE and FALSE values
np.object #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type

C:\Users\bhara\AppData\Local\Temp/ipykernel_4132/3377278132.py:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex #Complex numbers represented by 128 floats
C:\Users\bhara\AppData\Local\Temp/ipykernel_4132/3377278132.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool  #Boolean type storing TRUE and FALSE values
C:\Us

numpy.str_

# Array Mathematics 

In [54]:
g = a - b #Subtraction
np.subtract(a,b) #Subtraction
b + a #Addition 
np.add(b,a) #Addition 
a/b #Division 
np.divide(a,b) #Division 
a * b #Multiplication 
np.multiply(a,b) #Multiplication 
np.exp(b) #Exponentiation
np.sqrt(b) #Square root
np.sin(a)  #Print sines of an array
np.cos(b) #Elementwise cosine
np.log(a)#Elementwise natural logarithm
e.dot(f) #Dot product 


array([[7., 7.],
       [7., 7.]])

# Comparison

In [25]:
>>> a == b #Elementwise comparison


array([[False,  True,  True],
       [False, False, False]])

In [26]:
a< 2 #Elementwise comparison

array([ True, False, False])

In [27]:
np.array_equal(a, b) #Arraywise comparison

False

# Copying Arrays

In [28]:
h = a.view()#Create a view of the array with the same data
np.copy(a) #Create a copy of the array
h = a.copy() #Create a deep copy of the array

# Sorting Arrays

In [29]:
a.sort() #Sort an array
c.sort(axis=0) #Sort the elements of an array's axis

# Subsetting, Slicing, Indexing

In [30]:
a[2] #Select the element at the 2nd index

3

In [31]:
b[1,2] #Select the element at row 1 column 2(equivalent to b[1][2])

6.0

# Slicing

In [32]:
a[0:2]#Select items at index 0 and 1

array([1, 2])

In [33]:
b[0:2,1] #Select items at rows 0 and 1 in column 1

array([2., 5.])

In [35]:
b[:1]

array([[1.5, 2. , 3. ]])

In [36]:
c[1,...] #Same as[1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [37]:
a[ : : -1] #Reversed array a array([3, 2, 1])

array([3, 2, 1])

# Boolean Indexing

In [38]:
a[a<2] #Select elements from a less than 2

array([1])

# Fancy Indexing 

In [39]:
b[[1,0,1, 0],[0,1, 2, 0]] #Select elements(1,0),(0,1),(1,2) and(0,0)

array([4. , 2. , 6. , 1.5])

In [40]:
b[[1,0,1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

# Array Manipulation 
Transposing Array 

In [41]:
i = np.transpose(b) #Permute array dimensions
i.T #Permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

# Changing Array Shape 

In [42]:
b.ravel() #Flatten the array
g.reshape(3, -2) #Reshape, but don’t change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

# Adding/Removing Elements 

In [43]:
h.resize((2,6)) #Return a new arraywith shape(2,6)
np.append(h,g) #Append items to an array
np.insert(a,1,5)  #Insert items in an array
np.delete(a,[1])  #Delete items from an array


array([1, 3])

# Combining Arrays 



In [44]:
np.concatenate((a,d),axis=0) #Concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [50]:
np.vstack((a,b)) #Stack arrays vertically(row wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [46]:
np.r_[e,f] #Stack arrays vertically(row wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [47]:
np.hstack((e,f)) #Stack arrays horizontally(column wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [48]:
np.column_stack((a,d)) #Create stacked column wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [49]:
np.c_[a,d] #Create stacked column wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

# Splitting Arrays 



In [51]:
np.hsplit(a,3) #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [52]:
np.vsplit(c,2) #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]